Language: Default (ENG)
Style: Dark_Mode
LastApplied:
  SrcExe: D:/Project Ragnarok/ExperimentRO/Patcher/Client/2020-04-01bRagexe.exe
  TgtExe: D:/Project Ragnarok/ExperimentRO/Patcher/Client/ExperimentROv3.3.exe
Main:
  Width: 1920
  Height: 1017